### ISSUE TITLE
[Bug] Reloading config never completes

### ISSUE THREAD

**Issue by Smenon10** [toni-moreno/snmpcollector#202] opened 2017-05-03 19:52 UTC
Hello,
Since adding a lot more devices to my installation, I notice that the reload config never finishes. I have to stop/start the snmpcollector process on the server itself. 

using v0.7.0

logs are uploaded! Thanks

[logs.zip](https://github.com/toni-moreno/snmpcollector/files/974502/logs.zip)

**Comment by toni-moreno** [comment] 2017-05-03 20:32
Hi again and thank you to report this issue.

Can you be more precise?
How many are a lot ? And how long is never ?

**Comment by Smenon10** [comment] 2017-05-03 20:46
We currently have 100 devices, around 500-1500 metrics each.

Never meaning, I've let it run when I left work and the next morning it
still never reloaded

**Comment by toni-moreno** [comment] 2017-05-03 22:20
Hi @Smenon10 I've reviewed your logs and is really strange that related log to the reload process never happens on your log.

When reload is requested from the webui  these following lines should be shown in the log.

````
time="2017-05-03 23:54:06" level=info msg="trying to reload configuration for all devices" 
time="2017-05-03 23:54:06" level=info msg="RELOADCONF INIT: begin device Gather processes stop... at 2017-05-03 23:54:06.492660339 +0200 CEST" 
time="2017-05-03 23:54:06" level=info msg="RELOADCONF: begin selfmon Gather processes stop..." 
time="2017-05-03 23:54:06" level=info msg="RELOADCONF: waiting for all Gather gorotines stop..." 
time="2017-05-03 23:54:06" level=info msg="SELFMON: EXIT from SelfMonitoring Gather process " 
time="2017-05-03 23:54:06" level=info msg="RELOADCONF: releasing Device Resources" 
time="2017-05-03 23:54:06" level=info msg="RELOADCONF: releasing Seflmonitoring Resources" 
time="2017-05-03 23:54:06" level=info msg="RELOADCONF: begin sender processes stop..." 
time="2017-05-03 23:54:06" level=info msg="Stopping Influxdb out default" 
.... 
....
....
....
....
````

Are you sure you have sent us the correct agent log?

Anyway if you can reproduce the problem I would like you can send me the output of this URL before you restart it

````
http://<snmpcollector_host>:8090/debug/pprof/goroutine?debug=2
````
If a deadlock is happening this information will be really useful to review the problem.

**Comment by Smenon10** [comment] 2017-05-04 14:24
I'm seeing the below log when I hit the reload config button, but it hangs and no other logs are generated. I attached the web output as requested. 
[debug.zip](https://github.com/toni-moreno/snmpcollector/files/976426/debug.zip)

tail -f /var/log/messages | grep RELOAD
2017-05-04T14:21:51.486003+00:00 xxx-xxxx-xxxxxx snmpcollector: time="2017-05-04 14:21:51" level=info msg="RELOADCONF INIT: begin device Gather processes stop... at 2017-05-04 14:21:51.485115644 +0000 GMT"
^C

**Comment by toni-moreno** [comment] 2017-05-04 15:40
Hi Smenon I'm reviewing your info and I need some more information.

1- how many seconds have you configured for each gathering cycle? 
2- how long  are taking your devices to complete one cycle?
3 - have you configured the selfmon process?

Thank you.

**Comment by Smenon10** [comment] 2017-05-04 15:46
1- 10 seconds currently (seeing how low I can go before stuff stops working :))
2- how long are taking your devices to complete one cycle? (between 0.05 - 2 seconds, depends on distance)
3 - have you configured the selfmon process? I think so ..


[selfmon]
 #enable true/false enable/disable self monitoring
 enabled = true
 #send data Frequency
 freq = 60
 #prefix for measurement naming
 prefix = ""
 #adds extra tags to the measurement config should be set as a csv - tag=value1,tag2=value2,...,tagN=valN
 extratags = [ "instance=snmpcollector01" ]

**Comment by toni-moreno** [comment] 2017-05-05 09:27
Hi @Smenon10 we have never run the snmpcollector with less than 30 seconds for gathering cycle. It seems like a deadlock when very low cycle frequency is configured. I  will investigate next days.

Anyway I  would like some feedback on the snmpcollector behaviour when is running (without reload) with hundreds of devices and very low frequency configuration. How much memory ? How much cpu? how much stable is the gathering time?

**Comment by Smenon10** [comment] 2017-05-05 13:01
Hey!
Basically, snmpcollector in my environment is in POC. The goal was to get
really aggressive with polling because we want to just collect all the
data. Currently, we are at 120 devices (catalyst, nexus, aci, Netscaler,
ASR) and by the end we should be at around 150.

Initial setup is a VM running on 4 vcpu and 8 gigs of ram. This works fine
for data collection, load is low, gathering cycles from what I've seen is
stable. The only bug we ran into is the reload.

I'm currently in the process of upgrading the VM to 8 CPU and 32 gigs of
ram. The end goal is to put it on a physical server with 32 CPU, 256 gigs
of ram and a ton of SSD storage.

Overall, very impressed with the software and I really appreciate the quick
responses to my issues and questions!

On May 5, 2017 5:27 AM, "Toni Moreno" <notifications@github.com> wrote:

Hi @Smenon10 <https://github.com/Smenon10> we have never run the
snmpcollector with less than 30 seconds for gathering cycle. It seems like
a deadlock when very low cycle frequency is configured. I will investigate
next days.

Anyway I would like some feedback on the snmpcollector behaviour when is
running (without reload) with hundreds of devices and very low frequency
configuration. How much memory ? How much cpu? how much stable is the
gathering time?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/toni-moreno/snmpcollector/issues/202#issuecomment-299421067>,
or mute the thread

**Comment by toni-moreno** [comment] 2017-05-09 14:12
Hi @Smenon10 , I've just added some fixes related to deadlocks and race conditions. I was not able to reproduce your deadlock , but I suspect some of the related leak of data sharing control could be the origin of your deadlock. I hope you can test these new fixes when we can release a new version ( or now if yourself can build snmpcollector from source code) .

Anyway thanks a lot to report this.

**Comment by Smenon10** [comment] 2017-05-09 14:21
thank you very much, I will definitely be upgrading when it gets released!

**Comment by toni-moreno** [comment] 2017-05-17 22:09
Hi @Smenon10 We have finally released 0.7.1. 

Can you test again and reproduce this deadlock with the last version?

**Comment by pavleec** [comment] 2017-05-26 13:21
Hi @toni-moreno 

I've recently uprraded to 0.7.1 and I've noticed the same problems with configuration reloading like above. In my case it tooks over 10 minutes.

`time="2017-05-26` 15:16:49" level=info msg="RELOADCONF END: Finished from 2017-05-26 15:04:54.587989027 +0200 CEST to 2017-05-26 15:16:49.858103335 +0200 CEST [Duration : 11m55.270115236s]"`

**Comment by toni-moreno** [comment] 2017-05-26 13:31
@pavleec , @Smenon10 . 

We are developed in 0.7.2  a better communication system from webui to device goroutines , based on a broadcast bus .  I hope With next revision no deadlock happens and reload will spend less time than now.

@pavleec how big is your installation ?  how many devices /metrics / measurements ? and how long is taking devices to gather data?

@pavleec , @Smenon10 , we have uploaded 2 Grafana Dashboards that you can use to show device gathering statistics and  internal Golang VM process statitics. (https://github.com/toni-moreno/snmpcollector/wiki/Troubleshooting)   Feel Free to test to improve performance while waitting to the 0.7.2 release.

**Comment by Smenon10** [comment] 2017-05-26 13:45
Thanks for the dashboard, I'll take a look. This requires 0.7.1 to work? I haven't updated yet but might do so today.

**Comment by pavleec** [comment] 2017-05-26 21:00
My current setup consits of: 43 devices, 11k metrics and 2,5k measurements. I've checked statistics for all of the devices and found the one which was set to be polled every 2 min for which cycle gather duration sometimes was hitting over 3 mins. I've manually edited sqlite DB file, disabled the faulty device, restarted snmpcollector and GUI with it's settings reappeared again :) After that I've increased polling frequency to 5min and disabled ConcurrentGather what resulted in cycle duration drop to 25-30s. It appears then there is some kind of mentioned deadlock between successful finish of polling cycle and GUI responsivity.

Thanks for the provided Grafana dashboards. I've updated the custom one's that I was using.

**Comment by toni-moreno** [comment] 2017-05-26 22:04
Hi @pavleec , version 0.7.1 has introduced important fixes to data race conditions and mutex accessing. But also some unexpected and undesired  contentions  , that has been improved in 0.7.2  that I expect to release ASAP

**Comment by pavleec** [comment] 2017-05-26 22:11
Great, looking forward to test it then.

**Comment by toni-moreno** [comment] 2017-06-26 21:14
Hi @pavleec new release 0.7.3 has been released if you wha to test. Also would like to close this issue if fixed.

**Comment by toni-moreno** [comment] 2017-07-12 20:26
Hi @Smenon10 I would like to close this issue if you can now work fine with last 0.7.3 version

**Comment by toni-moreno** [comment] 2017-07-24 09:14
closed by the lack of feedback

**Closed by toni-moreno** 2017-07-24 09:14 UTC
