### ISSUE TITLE
[Bug] Assumption of time period when calculating rate

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#266] opened 2017-09-18 00:12 UTC
The calculate rate function (one of a few repeated snippets of code referenced below) uses the last time a sample was *attempted*. In the case where a sample isn't collected due an error, the period calculation fails and ends up producing a rate over a shorter period of time than the actual change in the counter occurred.

Rate function
https://github.com/toni-moreno/snmpcollector/blob/0e8a778fbb0e73bba755801cd214e435c69f1f6b/pkg/data/metric/snmpmetric.go#L186

Storage of LastTime doesn't take into account the fact that LastTime might be for a failed sample and thus is inaccurate.
https://github.com/toni-moreno/snmpcollector/blob/0e8a778fbb0e73bba755801cd214e435c69f1f6b/pkg/data/metric/snmpmetric.go#L177

**Comment by toni-moreno** [comment] 2017-09-20 08:30
Hi @tardoe . What exactly  mean "a failed sample" for you?.

If snmpcollector has a timeout , ( connection leak)  against some sequential gathering periods and can not get data for a specific counter the method  setRawData won't be executed againts these periods.  In  this case LastTime  won't be updated until a correct data. 

https://github.com/toni-moreno/snmpcollector/blob/0e8a778fbb0e73bba755801cd214e435c69f1f6b/pkg/data/metric/snmpmetric.go#L175-L184

Supose you have 1 minute as a gathering period and you have a connection leak for 1 minute , after the leak , the counter will be increased twice  the value for  , but also the elapsed time will be also twice the elapsed time for one period. After the leak the gathered point will be the mean value for the leak period.

If you saw a estrange value could be perhaps another use case.. or a bug but is not the expected behaviour

do you understand how counter updating is done in snmpcollector?

**Comment by tardoe** [comment] 2017-09-20 08:34
Yeah, I do understand how it's done. I'm just trying to trace why a missed sample resulting in the next sample being erroneous.

Regards,

Tim Raphael

**Comment by toni-moreno** [comment] 2017-09-22 06:00
Hi @tardoe  I will close this issue.

 Feel free to open another one when you can locate the source of your erroneus sample  from your debug logs.

**Closed by toni-moreno** 2017-09-22 06:00 UTC

**Comment by pchytla** [comment] 2017-09-28 23:22
I've the same problem with failed rate calculation , Example data from influxdb ( IfHcInOcetets , ifHCOutOctets) 

                                                                         IfHcInOcetets            ifHCOutOctets
2017-09-27T23:30:00.021Z WROC v256   14802.192717971764 1070125052.1021463
2017-09-27T23:35:00.015Z WROC v256   14246.295047537888 1013444223.8876053
2017-09-27T23:40:00.012Z WROC v256   14467.147001091336 992235605.0749829
2017-09-27T23:45:00.015Z WROC v256   40662.9925278471   491808024792718850
2017-09-27T23:50:00.013Z WROC v256   158033.82914331448 96136261.03421094
2017-09-27T23:55:00.012Z WROC v256   160317.38397527218 222541377.31762636
2017-09-28T00:00:00.011Z WROC v256   117531.15945074747 400431258.4136952
2017-09-28T00:05:00.013Z WROC v256   43463.69384816327  732443247.0404227

Value fHCOutOctets on timestamp "2017-09-27T23:45:00.015Z" is to high  for 10GE network interface, it cause on graph
very high peaks (492Pbps) like this https://imgur.com/qO0YQWC

Logs:
time="2017-09-28 01:45:06" level=info msg="MEASUREMENT [IFMIB-Octets64] Not EVAL metrics exist on  this measurement"
time="2017-09-28 01:45:06" level=info msg="MEASUREMENT [IFMIB-Octets64] Not Oid CONDITIONEVAL metrics exist on this measurement"
time="2017-09-28 01:45:10" level=info msg="MEASUREMENT [IFMIB-Octets64] Re Loading Indexed values"
time="2017-09-28 01:45:11" level=info msg="MEASUREMENT [IFMIB-Octets64] Applying filter : [ octets_multi1 ] on measurement"
time="2017-09-28 01:45:12" level=info msg="MEASUREMENT [IFMIB-Octets64] No changes on the filter OIDCondition "

octets_multi1 is filtering based on ifName and operstate value 

ifnamefilter = .1.3.6.1.2.1.31.1.1.1.1 notmatch "Vlanif|Vlan-interface"
ifoperstatefilter = .1.3.6.1.2.1.2.2.1.8 eq 1

 I've also think similar like @tardoe that CurValue can be unkown ( in my case when network interface change state to down) and that case very big value - LastValue/Elapsedtime only.

/pch

**Comment by toni-moreno** [comment] 2017-09-29 07:08
Hi @pchytla , We have also notice sometimes this buggy behaviour in some devices. But we have always checked that the problem were on some kind of reset on the counter, because of different causes, in our case a firmware upgrade, or some kind of management commands could perhaps reset the counters.

You can check if this is your case by only set the device in debug mode and search for the counter value before and  after the "peak".

As a workaround you can also change the counter type,  the COUNTERXX type for this kind of buggy systems or with unknown range .

`(Cooked type) COUNTERXX [Compute increments only if it really increments -- as NON_NEGATIVE_DERIVATIVE does--]`

Could you debug/test and give us some feedback please?

**Comment by pchytla** [comment] 2017-09-30 15:05
This  one is from Dlink DGS-3200-10 switch .

2017-09-30T09:35:00Z     KRAK 1/9       238501.47748136305 6434144.906895131
2017-09-30T09:40:00.001Z KRAK 1/9      367556.5075225548  9401323.16493514
2017-09-30T09:45:00Z     KRAK 1/9       126673279490.41512 9943529.950907972
                                                                     -----------------------
2017-09-30T09:50:00Z     KRAK 1/9       318019.7199898618  8451694.02767895
2017-09-30T09:55:00Z     KRAK 1/9       293341.1726087837  8083665.583084865

root@a2# snmpwalk -v2c  -cpublic KRAK ifName.9
IF-MIB::ifName.9 = STRING: 1/9

snmp debug : 

2017-09-30 11:40:00.65195 [SNMP-DEBUG] OID: .1.3.6.1.2.1.31.1.1.1.6.9
2017-09-30 11:40:00.65196 [SNMP-DEBUG] decodeValue: type is Counter64
2017-09-30 11:40:00.65196 [SNMP-DEBUG] decodeValue: value is 0x12db120bce8724
--
2017-09-30 11:45:00.65278 [SNMP-DEBUG] OID: .1.3.6.1.2.1.31.1.1.1.6.9
2017-09-30 11:45:00.65279 [SNMP-DEBUG] decodeValue: type is Counter64
2017-09-30 11:45:00.65279 [SNMP-DEBUG] decodeValue: value is 0x12df640ca1c446
--
2017-09-30 11:50:00.49942 [SNMP-DEBUG] OID: .1.3.6.1.2.1.31.1.1.1.6.9
2017-09-30 11:50:00.49943 [SNMP-DEBUG] decodeValue: type is Counter64
2017-09-30 11:50:00.49943 [SNMP-DEBUG] decodeValue: value is 0x12df640d57bd27
--
2017-09-30 11:55:00.65351 [SNMP-DEBUG] OID: .1.3.6.1.2.1.31.1.1.1.6.9
2017-09-30 11:55:00.65351 [SNMP-DEBUG] decodeValue: type is Counter64
2017-09-30 11:55:00.65352 [SNMP-DEBUG] decodeValue: value is 0x12df640dff970b

For sure this one have buggy counter .

/pch
