### ISSUE TITLE
InfluxDB write error

### ISSUE THREAD

**Issue by vkosilko** [toni-moreno/snmpcollector#22] opened 2016-10-26 11:12 UTC
In 0.5.1 release have such errors for several devices:
```
INFO[2016-10-26 12:34:07] beggining Influx Emmiter thread: 5577006791947779410 
INFO[2016-10-26 12:34:07] Server is running on localhost:8090...       
ERRO[2016-10-26 12:34:07] influxdb write error:  {"error":"partial write:\nunable to parse 'Counters,ifIndex=11439,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value\nunable to parse 'Counters,ifIndex=10088,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value\nunable to parse 'Counters,ifIndex=10001,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value\nunable to parse 'Counters,ifIndex=8193,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value"}
ERRO[2016-10-26 12:34:37] influxdb write error:  {"error":"partial write:\nunable to parse 'Counters,ifIndex=11439,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value\nunable to parse 'Counters,ifIndex=10088,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value\nunable to parse 'Counters,ifIndex=10001,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value\nunable to parse 'Counters,ifIndex=8193,router=sw127x142_N69_SKD ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value"}
```
It seem that errors appear only for VLAN interfaces:
```
IF-MIB::ifName.8193 = STRING: ifc8193 (Slot: 11 Port: 2)
IF-MIB::ifName.10001 = STRING: ifc10001 VLAN #1
IF-MIB::ifName.10088 = STRING: ifc10088 VLAN #88
IF-MIB::ifName.11439 = STRING: ifc11439 VLAN #1439
```
We didn't have such errors in previous snmpcollector releases.

**Comment by vkosilko** [comment] 2016-10-26 14:06
Problem can be solved by adding port filtering, for example:
Device port names:
```
iso.3.6.1.2.1.31.1.1.1.1.1 = STRING: "Vl1"
iso.3.6.1.2.1.31.1.1.1.1.40 = STRING: "Vl40"
iso.3.6.1.2.1.31.1.1.1.1.10001 = STRING: "Fa0/1"
iso.3.6.1.2.1.31.1.1.1.1.10002 = STRING: "Fa0/2"
iso.3.6.1.2.1.31.1.1.1.1.10003 = STRING: "Fa0/3"
```
Filter:
`INSERT INTO meas_filter_cfg (id,id_measurement_cfg,filter_type,cond_oid,cond_type,cond_value) VALUES ('vl_filter','Counters','OIDCondition','.1.3.6.1.2.1.31.1.1.1.1','match','Fa.*');
`
Need more universal decision.

**Comment by toni-moreno** [comment] 2016-10-26 14:48
This error means there is not values in the SNMP response , so when the collector build the influxdb query it has not any value in memory. I will add a check before send , but this only will hide the influxdb client error .

The important question is about missing data on these interfaces.

Can you do a snmpget over  on the affected OID's to see what really is responding ?

this is
```
snmpget -v2c -c <your_community> <yourhost> IF-MIB::ifHCInOctets.10001
snmpget -v2c -c <your_community> <yourhost> IF-MIB::ifHCOutOctets.10001
etc
```

**Comment by vkosilko** [comment] 2016-10-27 16:03
I made some tests for device:
```
# snmpbulkwalk -c public -v 2c 172.26.40.5 .1.3.6.1.2.1.31.1.1.1.1
iso.3.6.1.2.1.31.1.1.1.1.1 = STRING: "Vl1"
iso.3.6.1.2.1.31.1.1.1.1.40 = STRING: "Vl40"
iso.3.6.1.2.1.31.1.1.1.1.10001 = STRING: "Fa0/1"
iso.3.6.1.2.1.31.1.1.1.1.10002 = STRING: "Fa0/2"
...
```
I can get ifHCInOctets for it:
```
# snmpbulkwalk -c public -v 2c 172.26.40.5 .1.3.6.1.2.1.31.1.1.1.6
iso.3.6.1.2.1.31.1.1.1.6.1 = Counter64: 34184
iso.3.6.1.2.1.31.1.1.1.6.40 = Counter64: 17563913324
iso.3.6.1.2.1.31.1.1.1.6.10001 = Counter64: 492843318
iso.3.6.1.2.1.31.1.1.1.6.10002 = Counter64: 129397552
iso.3.6.1.2.1.31.1.1.1.6.10003 = Counter64: 25644
```
When I run collector, I see influxdb write error every 30 seconds:
```
ERRO[2016-10-27 12:25:31] influxdb write error:  {"error":"partial write:\nunable to parse 'Counters,ifIndex=10501,router=myrouter ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=,ifHCInUcastPkts=,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=,ifHCOutUcastPkts=': missing field value\nunable to parse 'Counters,ifIndex=1,router=myrouter ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=34184,ifHCInUcastPkts=152,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=0,ifHCOutUcastPkts=0 1477585351245511248': missing field value\nunable to parse 'Counters,ifIndex=40,router=myrouter ifHCInBroadcastPkts=,ifHCInMulticastPkts=,ifHCInOctets=17563957551,ifHCInUcastPkts=160046822,ifHCOutBroadcastPkts=,ifHCOutMulticastPkts=,ifHCOutOctets=9514178311,ifHCOutUcastPkts=34981928 1477585351245511248': missing field value"}
```

Collector stops sending data to influxdb after error appeared:
There is only one record for 10001 ifIndex:
> select * from Counters where ifIndex = '10001'
```
name: Counters
--------------
time			ifHCInBroadcastPkts	ifHCInMulticastPkts	ifHCInOctets	ifHCInUcastPkts	ifHCOutBroadcastPkts	ifHCOutMulticastPkts	ifHCOutOctets		ifHCOutUcastPkts	ifIndex	router
1477585351245511248	984620			717033			4.92857842e+08	127707		8.714503e+07		8.9192184e+07		1.4805549423e+10	8.698373e+06		10001	myrouter```

When I add ifName condition filter and collect data only from physical ports:
I don't have error, and data writes fine: 
> select * from Counters where ifIndex = '10001'
```
name: Counters
--------------
time			ifHCInBroadcastPkts	ifHCInMulticastPkts	ifHCInOctets	ifHCInUcastPkts	ifHCOutBroadcastPkts	ifHCOutMulticastPkts	ifHCOutOctets		ifHCOutUcastPkts	ifIndex	router
1477592167067706370	984997			717147			4.93007892e+08	127707		8.7158741e+07		8.9196976e+07		1.4806904374e+10	8.699063e+06		10001	myrouter
1477592287071127901	985003			717149			4.93010312e+08	127707		8.7158861e+07		8.9197056e+07		1.4806920816e+10	8.699075e+06		10001	myrouter
1477592407068034543	985009			717151			4.93012732e+08	127707		8.7158952e+07		8.9197134e+07		1.4806933833e+10	8.699087e+06		10001	myrouter
```
I can't create filters for all devices, so we need to collect data from port in spite of errors.

**Comment by toni-moreno** [comment] 2016-10-27 21:19
Hi @vkosilko first I would like to say I am very grateful for the time that these using in helping debug this tool.

After review the logs I've notice that values are correct , and I realized that I did a change in past commits to data type sent. I think the problem comes on how data is interpreted for golang runtime when it come with 0 values ( perhaps as integer or as void string) . (two first values are 9514178311, so the computed difference is 0 see 2 first "value" below).

I've added a casting to force float as type (https://github.com/toni-moreno/snmpcollector/blob/master/pkg/influxmeasurement.go#L287)

````
developer@snmpcoldev01:~/Descargas$ grep "\.10\.40" test_no_filter/myrouter.log 
DEBU[0000] received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.10.40 Type:70 Value:9514178311 Logger:0xc8201d60f0} 
DEBU[0000] received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.10.40 Type:70 Value:9514178311 Logger:0xc8201d60f0} 
DEBU[0120] received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.10.40 Type:70 Value:9514196753 Logger:0xc8201d60f0} 
DEBU[0240] received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.10.40 Type:70 Value:9514205365 Logger:0xc8201d60f0} 
````

I think the problem is fixed now,  anyway I've added a improved debug log to take more accurate data to continue reviewing this issue if not fixed.

I hope you can test again and help me to debug  if problem persist. 

Thank you very much again.

**Comment by vkosilko** [comment] 2016-10-28 07:55
@toni-moreno unfortunatly, there are some errors while starting collector:
```
panic: interface conversion: interface is nil, not float64
goroutine 6 [running]:
panic(0xc0e540, 0xc820069980)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*InfluxMeasurement).GetInfluxPoint(0xc8202284d0, 0xc8201dd9e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/github.com/toni-moreno/pkg/influxmeasurement.go:286 +0x1bc0
main.(*SnmpDevice).Gather(0xc8201de1c0, 0xc82000a1f0)
	/usr/local/go/src/github.com/toni-moreno/pkg/snmpdevice.go:438 +0x18e7
created by main.main
	/usr/local/go/src/github.com/toni-moreno/pkg/main.go:278 +0x12a
```

**Comment by toni-moreno** [comment] 2016-10-28 08:12
@vkosilko send me all generated logs please. 

The fix was not good but the problem was completely located  and is about data tranformation  what  I suposed yerterday. With your logs you will give me needed information.

Thank you again

**Comment by vkosilko** [comment] 2016-10-28 08:46
@toni-moreno problem is in meas_filter_cfg table.
For such condition:
`INSERT INTO meas_filter_cfg (id,id_measurement_cfg,filter_type,cond_oid,cond_type,cond_value) VALUES ('test','Counters','OIDCondition','.1.3.6.1.2.1.31.1.1.1.1','match','Fa*');`
data writes to influxdb.
If I delete filter record - I get error above.
If I set condition as "*" - I see no data in influxdb.

How to setup filter to write all data?

**Comment by toni-moreno** [comment] 2016-10-28 09:00
set cond_value  => "Fa.*" (should be a valid regular expresion)  with "dot"

**Comment by toni-moreno** [comment] 2016-10-28 09:01
anyway I'm working right now in a workaround to avoid type conversion as did before last week. So you will have a patch soon...

**Comment by vkosilko** [comment] 2016-10-28 09:05
Filtered ports logs: https://drive.google.com/open?id=0B0rkzfzNglIwZklzbGVpeU52RjQ
Not filtered ports logs: https://drive.google.com/open?id=0B0rkzfzNglIwZVVjdVFuOHp1QjA

**Comment by toni-moreno** [comment] 2016-10-28 11:56
Hi @vkosilko  with your logs and new test , I've myself could reproduced the problem in a switch with VLAN's

And What I've seen is some of selected fields has no return values for some metrics:

- ifHCOutBroadcastPkts
- ifHCOutMulticastPkts
- ifHCInMulticastPkts
- ifHCInBroadcastPkts 

The log
````
time="2016-10-28 13:44:16" level=error msg="MEASUREMENT[ SAN_CISCO_ISL_Throughput ]  METRIC ID [ifHCOutBroadcastPkts] Runtime [ &{cfg:0xc8201ade30 ID:ifHCOutBroadcastPkts CookedValue:<nil> curValue:0 lastValue:0 CurTime:0001-01-01 00:00:00 +0000 UTC lastTime:{sec:0 nsec:0 loc:<nil>} Compute:0x448890 setRawData:0x4484a0 RealOID:.1.3.6.1.2.1.31.1.1.1.13.1915} ]"
time="2016-10-28 13:44:16" level=error msg="MEASUREMENT[ SAN_CISCO_ISL_Throughput ]  METRIC ID [ifHCOutMulticastPkts] Runtime [ &{cfg:0xc8201adea0 ID:ifHCOutMulticastPkts CookedValue:<nil> curValue:0 lastValue:0 CurTime:0001-01-01 00:00:00 +0000 UTC lastTime:{sec:0 nsec:0 loc:<nil>} Compute:0x448890 setRawData:0x4484a0 RealOID:.1.3.6.1.2.1.31.1.1.1.12.1915} ]"
time="2016-10-28 13:44:16" level=error msg="MEASUREMENT[ SAN_CISCO_ISL_Throughput ]  METRIC ID [ifHCInMulticastPkts] Runtime [ &{cfg:0xc8201add50 ID:ifHCInMulticastPkts CookedValue:<nil> curValue:0 lastValue:0 CurTime:0001-01-01 00:00:00 +0000 UTC lastTime:{sec:0 nsec:0 loc:<nil>} Compute:0x448890 setRawData:0x4484a0 RealOID:.1.3.6.1.2.1.31.1.1.1.8.1915} ]"
time="2016-10-28 13:44:16" level=error msg="MEASUREMENT[ SAN_CISCO_ISL_Throughput ]  METRIC ID [ifHCInBroadcastPkts] Runtime [ &{cfg:0xc8201adce0 ID:ifHCInBroadcastPkts CookedValue:<nil> curValue:0 lastValue:0 CurTime:0001-01-01 00:00:00 +0000 UTC lastTime:{sec:0 nsec:0 loc:<nil>} Compute:0x448890 setRawData:0x4484a0 RealOID:.1.3.6.1.2.1.31.1.1.1.9.1915} ]"
```
See yourself the test with snmpget

```
# snmpget -v2c -c  public mytestswitch 1.3.6.1.2.1.31.1.1.1.13.1915
IF-MIB::ifHCOutBroadcastPkts.1915 = No Such Instance currently exists at this OID
```
I will write a patch for these cases where some of the selected fields could not exist .

**Comment by toni-moreno** [comment] 2016-10-28 12:35
@vkosilko , I hope now to be completely fixed this issue  !! .

Thanks a lot !!

**Comment by vkosilko** [comment] 2016-10-28 14:18
@toni-moreno Thank you for fast bug fixing) It seem to be working!

**Closed** 2016-10-28 14:18 UTC
