### ISSUE TITLE
[Bug] Version 0.7.1 glitches 

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#218] opened 2017-05-26 13:46 UTC
Hi,

I've upgraded to the 0.7.1 and noticed some strange bahavior:
- no configuration data or device status are visible - they usually appeared after some time but I've just added one new device and they are not displayed anymore despite the fact that all SNMP stats are collected properly
- configuration reload tooks "forever" - usually around 10-15 min (already mentioned in #202)
- logout button is not working

There were no such problems on v.0.7.0.

**Comment by Smenon10** [comment] 2017-05-26 14:05
I can confirm the first bug, no config data or device status are visible. All data is collected though as my graphs are still working fine. 
Logout button works fine for me though.

**Comment by toni-moreno** [comment] 2017-05-26 14:13
It seems like something happens in the client side.
Have you deleted all browser cached data after the update? Could you show us the logs/errors i  the browser console ?.

**Comment by Smenon10** [comment] 2017-05-26 14:37
I tried in incognito mode, screenshot attached.

![image](https://cloud.githubusercontent.com/assets/27831991/26499109/61a6b874-41ff-11e7-9812-9a1c60b2bb93.png)

**Comment by toni-moreno** [comment] 2017-05-26 15:00
The request is never finishing ... isn't it ?.

Can you describe us what you did since you login until this happens ?   

What happens if you select any other item in  the sidebar menu while waiting this request ?

**Comment by Smenon10** [comment] 2017-05-26 15:51
It ends up finishing, takes up to 1 minute. It seems like the same on all
the menu options, seems like a 1 minute delay on everything.

On May 26, 2017 11:00 AM, "Toni Moreno" <notifications@github.com> wrote:

The request is never finishing ... isn't it ?.

Can you describe us what you did since you login until this happens ?

What happens if you select any other item in the sidebar menu while waiting
this request ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/toni-moreno/snmpcollector/issues/218#issuecomment-304305756>,
or mute the thread

**Comment by pavleec** [comment] 2017-05-26 21:10
I think I've managed to identify the root cause of the first and third mentioned bug - one device in my configuration many times was responding slower then it's defined polling frequency (2 mins). Details described in #202.

**Comment by tardoe** [comment] 2017-05-27 01:41
I’ve noticed this as well. The data being filled in the frontend takes around 1 minute after a reload.

- Tim

**Comment by toni-moreno** [comment] 2017-05-27 04:42
@tardoe , @pavleec  , @Smenon10  I've just released and uploaded new 0.7.2 version . I hope you can now work better with the snmpcollector and we can definitely close this issue!!

Anyway from 0.7.1 version when we want to see online data and click on the selected device on the web-ui we will need to wait for this device finish it's gathering process if it has already began. This is needed to avoid race conditions and the only way to see consistent data on the web-ui.(previous versions we are showing mixed data from two consecutive gather calls , and sometimes incorrect data when a race condition happened) . Big devices sometimes takes near 1 minute to take all it's data, in those devices we always will have to wait a lot. There is not workaround for that. I'm sorry.

Let me know if I can close this and #202 issues.

**Comment by toni-moreno** [comment] 2017-05-27 05:37
About what I said before.. 

_"There is not workaround for that..."_ 

This is not strictly true. Indeed exist a way to avoid this contentions, and consist on have a duplicate set of data ( accessible while updating the original set of data)  continuously in memory and updated on each gathering process. 

The cost of this workaround will be duplicate needed memory of the process. I won't like duplicate needed resources if 99.99%  of the life cycle on the snmpcollector running process It won't need it and  90% of devices can gather its data below 10 seconds. ( I'm currently gathering near 500 devices , and only 3 or 4 have gathering times over 20 seconds ).

@pavleec , @sbengo , @Smenon10 , @tardoe  Are you agree? what do you think about?

**Comment by pavleec** [comment] 2017-05-28 21:36
@toni-moreno, I think it's completely fine and clear that there would be a delay in real time data browsing. Only the lack of current configuration is irritating. It might always happen that there would be some faulty or slow responding device for which snmpcollector should be somehow secured against.

**Comment by toni-moreno** [comment] 2017-07-12 20:29
Hi @pavleec  I would like to close this issue if you can now work fine with last 0.7.3 version (from main runtime table you will be able to test and view device state , the detail only needed to check for measurements /metric values).

**Comment by toni-moreno** [comment] 2017-07-24 09:14
Closed by lack of feedback.

**Closed by toni-moreno** 2017-07-24 09:14 UTC
